//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Year2018.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Year2018.Test.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -14
        ///-9
        ///-14
        ///-12
        ///+13
        ///+2
        ///+7
        ///-18
        ///+10
        ///-8
        ///+13
        ///+12
        ///+11
        ///-1
        ///+9
        ///+3
        ///+6
        ///-1
        ///+11
        ///-9
        ///-6
        ///+11
        ///-3
        ///+18
        ///-7
        ///+13
        ///-11
        ///+18
        ///+10
        ///+9
        ///+16
        ///+11
        ///+14
        ///-19
        ///+14
        ///-3
        ///-8
        ///-5
        ///-10
        ///-18
        ///-9
        ///-10
        ///+6
        ///+8
        ///+10
        ///+10
        ///-19
        ///+18
        ///+17
        ///-14
        ///+4
        ///+2
        ///+4
        ///-17
        ///+3
        ///-9
        ///-16
        ///-16
        ///+7
        ///+7
        ///+21
        ///+13
        ///-11
        ///+17
        ///+11
        ///+1
        ///+19
        ///-4
        ///+6
        ///-7
        ///-13
        ///-10
        ///+11
        ///-4
        ///-2
        ///-22
        ///-9
        ///+8
        ///-19
        ///-12
        ///-13
        ///-8
        ///-16
        ///-4
        ///-14
        ///-8
        ///-1
        ///+7
        ///+11
        ///-4
        ///-4
        ///-6
        ///-13
        ///-12
        ///-11
        ///-19
        ///-3
        ///+10
        ///+1
        ///+19
        ///+12
        ///+9
        ///-12
        ///+4
        ///+16
        ///+14
        ///+1
        ///-8
        ///-9
        ///+5
        ///+17
        ///+12
        ///-20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputD1P1 {
            get {
                return ResourceManager.GetString("InputD1P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ivyhczwokexltwhsfamqprbnuy
        ///ivjhcjdokexltwwsfamqpabnuy
        ///ivjhczdokebltwgsfydqprbnuy
        ///ivjhcadokexftogsfamqprbnuy
        ///idjhczdokexltwgsfacqprbnuh
        ///ivjhgzookexltwgsfamqjrbnuy
        ///uvjhctdokexltwosfamqprbnuy
        ///ivrhczdokexltwhzfamqprbnuy
        ///ivjhczuxkexltwgsfamqprbney
        ///ivjhczdokemltwgsfadnprbnuy
        ///ifjhczdokexltwgsfamqprbkuf
        ///ivjhkzdokltltwgsfamqprbnuy
        ///ivjuczdhkexltwgsfamqprtnuy
        ///ivjhjzdxkexltwgsfapqprbnuy
        ///ivlhczdoxexltwgsfamqprgnuy
        ///ivjhczdoknxltwgssamqsrbnuy
        ///ivjhczdokexltwgswadqprbruy
        ///ivjhczdokexthwgsfampprbnuy
        ///uvjhczro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputD2P1 {
            get {
                return ResourceManager.GetString("InputD2P1", resourceCulture);
            }
        }
    }
}
