//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Year2019 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Year2019.InputFiles", typeof(InputFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 142388
        ///128965
        ///137791
        ///93517
        ///98732
        ///83948
        ///64037
        ///124603
        ///61093
        ///132020
        ///99227
        ///73227
        ///75536
        ///53249
        ///149300
        ///75975
        ///146023
        ///117855
        ///105380
        ///127149
        ///146894
        ///73257
        ///69233
        ///67090
        ///87932
        ///107473
        ///127873
        ///132999
        ///139324
        ///92861
        ///83651
        ///91064
        ///137074
        ///94188
        ///96969
        ///96592
        ///116019
        ///52969
        ///125456
        ///97428
        ///112642
        ///99901
        ///89405
        ///91983
        ///56445
        ///64917
        ///72393
        ///127679
        ///122430
        ///142036
        ///87228
        ///118322
        ///51965
        ///67787
        ///130183
        ///124044
        ///101324
        ///107800
        ///85585
        ///67886
        ///140772
        ///138280
        ///73183
        ///116096
        ///79239
        ///105958
        ///92719
        ///70896
        ///115279
        ///51912
        ///74396
        ///75121
        ///131819
        ///67970
        ///96436
        ///107074
        ///135588
        ///97510
        ///57877
        ///114 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day_01_01 {
            get {
                return ResourceManager.GetString("day_01_01", resourceCulture);
            }
        }
    }
}
