//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Year2019 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Year2019.InputFiles", typeof(InputFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 142388
        ///128965
        ///137791
        ///93517
        ///98732
        ///83948
        ///64037
        ///124603
        ///61093
        ///132020
        ///99227
        ///73227
        ///75536
        ///53249
        ///149300
        ///75975
        ///146023
        ///117855
        ///105380
        ///127149
        ///146894
        ///73257
        ///69233
        ///67090
        ///87932
        ///107473
        ///127873
        ///132999
        ///139324
        ///92861
        ///83651
        ///91064
        ///137074
        ///94188
        ///96969
        ///96592
        ///116019
        ///52969
        ///125456
        ///97428
        ///112642
        ///99901
        ///89405
        ///91983
        ///56445
        ///64917
        ///72393
        ///127679
        ///122430
        ///142036
        ///87228
        ///118322
        ///51965
        ///67787
        ///130183
        ///124044
        ///101324
        ///107800
        ///85585
        ///67886
        ///140772
        ///138280
        ///73183
        ///116096
        ///79239
        ///105958
        ///92719
        ///70896
        ///115279
        ///51912
        ///74396
        ///75121
        ///131819
        ///67970
        ///96436
        ///107074
        ///135588
        ///97510
        ///57877
        ///114 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day_01_01 {
            get {
                return ResourceManager.GetString("day_01_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,0,0,3,1,1,2,3,1,3,4,3,1,5,0,3,2,1,10,19,1,19,5,23,1,6,23,27,1,27,5,31,2,31,10,35,2,35,6,39,1,39,5,43,2,43,9,47,1,47,6,51,1,13,51,55,2,9,55,59,1,59,13,63,1,6,63,67,2,67,10,71,1,9,71,75,2,75,6,79,1,79,5,83,1,83,5,87,2,9,87,91,2,9,91,95,1,95,10,99,1,9,99,103,2,103,6,107,2,9,107,111,1,111,5,115,2,6,115,119,1,5,119,123,1,123,2,127,1,127,9,0,99,2,0,14,0
        ///.
        /// </summary>
        internal static string day_02_01 {
            get {
                return ResourceManager.GetString("day_02_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R998,U547,L703,D251,L776,U837,R100,U240,R197,D216,L220,U606,L437,U56,R940,U800,L968,D464,L870,D797,L545,D824,R790,U5,R347,D794,R204,U538,L247,U385,L103,D260,L590,U813,L549,U309,L550,U321,R862,D686,R368,D991,R451,D836,R264,D138,L292,D319,L784,D369,R849,U865,R776,D726,R223,D118,L790,D208,L836,D592,R310,D36,R991,U674,L205,U407,R422,U350,L126,D320,L239,U353,L509,U48,R521,D544,L157,D551,R614,D493,R407,D965,R498,U248,R826,U573,L782,D589,R616,D992,L806,D745,R28,U142,L333,D849,L858,D617,R167,U341,R46,U940,L615,D997 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day_03_01 {
            get {
                return ResourceManager.GetString("day_03_01", resourceCulture);
            }
        }
    }
}
